config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Send back the home page
  get "pages/index"
  root to: "pages#index"
  
  # Send back all addresses to the client for Admin use
  get 'addresses', to: 'addresses#index'
  # Create new addresses
  post 'addresses', to: 'addresses#create'
  get 'addresses/new', to: 'addresses#new'
  # Send back one address to the client
  get 'addresses/:id', to: 'addresses#show', as: 'address'
  # Edit an address
  get 'addresses/:id/edit', to: 'addresses#edit', as: "edit_address"
  patch 'addresses/:id', to: 'addresses#update'
  put 'addresses/:id', to: 'addresses#update'
  
  get '/mypurchases', to: 'purchases#index', as: "my_purchases"
  
  # Search for games 
  get '/search', to: 'games#search'
  resources :games do
    resources :purchases, only:[:new, :create, :index]
  end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
    
    before_action :find_purchase, only: %i[show edit update destroy ]
    before_action :find_game, only: [:new, :create ]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    before_action :check_ownership, only: [:edit, :update, :destroy]

    def index
        @purchases = current_user.purchases
    end


    def new
        @purchase = Purchase.new
    end

    def create
        # assign an amount value which can later be adjusted for discounts and shipping costs
        @amount = (@game.price*100).to_i
        customer = Stripe::Customer.create(
            email: params[:stripeEmail],
            source: params[:stripeToken]
        )
        # Make a charge for Stripe giving it the data it needs
        charge = Stripe::Charge.create(
            customer: customer.id,
            amount: (@game.price*100).to_i,
            description: "#{@game.name} payment",
            currency: 'aud'
        )
        # Add the purchase data to the table including the url for the receipt from Stripe
        begin
        @purchase = Purchase.create(game: @game, user: current_user, price: @game.price, receipt_url: charge.receipt_url)
        # redirect_to game_path(@game.id)
        @purchase.game.update(sold: true)
        rescue Stripe::CardError => e
            puts e.message
            # flash[:error] = e.message
            redirect_to game_path(@game.id), alert: "Payment failed" 
        end
        @purchase.game.update(sold: true)
    end

    private

    def find_game
        @game = Game.find(params[:game_id])
    end

    def find_purchase
        @purchase = Purchase.find(params[:purchase_id])
    end
    # As with this code in other controllers, only let the right people access functions
    def check_ownership
        if !(current_user.admin? or current_user.id == @purchase.user_id)
          redirect_to games_url, alert: "You have to be the seller of a game or an admin to do this."
        end
      end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/create.html.erb
<h3>Thank you for your payment of $<%=@purchase.price%> for <%=@game.name%></h3>
<p>We hope you enjoy your new game</p>

app/views/purchases/index.html.erb
<h1>My purchase history</h1>

<% @purchases.each do |p| %>
    <h3><%=p.game.name%></h3>
    <p>$<%=p.price%></p>
    <p>Purchased on: <%=p.created_at%></p>
    <%= link_to "See receipt", "#{p.receipt_url}", target: :_blank, class: "btn btn-primary my-2" %>
    
    <br>
<% end %>

app/views/purchases/new.html.erb
<p>Are you sure you want to buy <%=@game.name%>?</p>

<%= form_tag game_purchases_path do %>
    <article>
        <% if flash[:error].present? %>
            <div id="error_explanation">
                <p><%= flash[:error] %></p>
            </div>
        <% end %>

        <label class="amount">
            <span>Amount: $<%= @game.price %></span>
        </label>
    </article>
    
    <div>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Payment for game"
            data-amount="<%=(@game.price*100).to_i%>"
            data-locale="auto">
        </script>
    
        <a href="<%= game_path(@game.id) %>" class="btn btn-secondary my-2">Cancel</a>
    </div>
<% end %>