config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Send back the home page
  get "pages/index"
  root to: "pages#index"
  
  # Send back all addresses to the client for Admin use
  get 'addresses', to: 'addresses#index'
  # Create new addresses
  post 'addresses', to: 'addresses#create'
  get 'addresses/new', to: 'addresses#new'
  # Send back one address to the client
  get 'addresses/:id', to: 'addresses#show', as: 'address'
  # Edit an address
  get 'addresses/:id/edit', to: 'addresses#edit', as: "edit_address"
  patch 'addresses/:id', to: 'addresses#update'
  put 'addresses/:id', to: 'addresses#update'
  
  get '/mypurchases', to: 'purchases#index', as: "my_purchases"
  
  # Search for games 
  get '/search', to: 'games#search'
  resources :games do
    resources :purchases, only:[:new, :create, :index]
  end

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <!-- Page heading -->
        <nav class="navbar navbar-light bg-dark">
            <% # Site name in navbar %>
            <div class="container-fluid">
                <span class="navbar-brand mb-0 h1">Bored-Games</span>
            </div>
        </nav>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <% # Navbar contents %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
                <% # Link to home page %>
                <li class="nav-item">
                    <%= link_to "Home", pages_index_path, class: "nav-link active" %> 
                </li>

                <% # Link to games index page %>
                <li class="nav-item">
                    <%= link_to "See all games", games_path, class: "nav-link active" %> 
                </li>
            </ul>
            <% # Search_field and button %>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li>
                <%= form_tag(search_path, :method => "get") do %>
                    <div class="input-group">
                        <%= search_field_tag :search, params[:search], placeholder: "Search games by name", class: "form-control" %>
                        <div class="input-group-btn">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </div>
                    </div>
                <% end %>
                </li>
            </ul>

            <% # Condition changes contents for logged in or not %>
            <% if user_signed_in? %>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">        
                    <% # Options for logged in users %>
                    <li class="nav-item">
                        <%= link_to "Sell my game", new_game_path, class: "nav-link active" %>
                    </li>
                </ul>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">    
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <%=current_user.username %>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><%= link_to "My details", current_user.address, class: "dropdown-item" %></li>
                            <li><%= link_to "Purchase history", my_purchases_path, class: "dropdown-item" %></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><%= link_to "Logout", destroy_user_session_path, method: 'delete', class: "dropdown-item"  %></li>
                        </ul>
                    </li>
                </ul>
            
                <% # Options for guests and not logged in %>
            <% else %>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <%= link_to "Sign in", new_user_session_path, class: "nav-link active" %>
                    </li>

                    <li class="nav-item">
                        <%= link_to "Sign up", new_user_registration_path, class: "nav-link active" %>
                    </li>
                </ul>
            <% end %> 
            </ul>
            
        </div>
    </div>
</nav>
<br>