config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Send back the home page
  get "pages/index"
  root to: "pages#index"
  
  # Send back all addresses to the client for Admin use
  get 'addresses', to: 'addresses#index'
  # Create new addresses
  post 'addresses', to: 'addresses#create'
  get 'addresses/new', to: 'addresses#new'
  # Send back one address to the client
  get 'addresses/:id', to: 'addresses#show', as: 'address'
  # Edit an address
  get 'addresses/:id/edit', to: 'addresses#edit', as: "edit_address"
  patch 'addresses/:id', to: 'addresses#update'
  put 'addresses/:id', to: 'addresses#update'
  
  get '/mypurchases', to: 'purchases#index', as: "my_purchases"
  
  # Search for games 
  get '/search', to: 'games#search'
  resources :games do
    resources :purchases, only:[:new, :create, :index]
  end

end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :users
  has_one :purchase
    # for adding a picture
  has_one_attached :picture

  # Enums for the condition and genre of the games 
    # conditions some damage, incomplete, good, well looked after, brand new
    # {"some damage" => 1, "incomplete" => 2, "good" => 3, "well looked after" => 4, "brand new" => 5}
    enum condition: {some_damage: 1, incomplete: 2, good: 3, well_looked_after: 4, brand_new: 5}

    # genres sci-fi/fantasy, family, strategy, RPG, worker placement, co-op
    # {"sci-fi/fantasy" => 1, "family" => 2, "strategy" => 3, "RPG" => 4, "worker placement" => 5, "co-op" => 6}
    enum genre: {science_fiction: 1, fantasy: 2, family: 3, strategy: 4, RPG: 5, worker_placement: 6, co_op: 7}

  

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :find_game, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :check_ownership, only: [:edit, :update, :destroy]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /search
  def search
    if params[:search].blank?
      redirect_to games_path and return
    else
        @parameter = params[:search].downcase
        @results = Game.all.where("lower(name) LIKE :search", search: "%#{@parameter}%")
    end
  end

  # GET /games/1
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # def create
  #   begin
  #     game = current_user.games.create(game_params)
  #     redirect_to game_path(game), notice: "#{game.name} was created successfully"
  #   rescue StandardError => e
  #     puts e.message
  #     redirect_to games_path, notice: "#{game.name} wasn't created"
  #   end
  # end
  def create
    begin
      game = current_user.games.create(game_params)
      redirect_to game_path(game), notice: "#{game.name} was created successfully"
    rescue StandardError => e
      puts e.message
      redirect_to games_path, notice: "Game wasn't created"
    end
  end

  # PATCH/PUT /games/1
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to games_url(@game), notice: "Game was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    puts "destroy"
    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_game
      begin
        @game = Game.find(params[:id])
      rescue StandardError => e
        puts e.message
        redirect_to games_path, alert: "This game id #{params[:id]} doesn't exist in the database"
      end
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name, :condition, :minimum_players, :maximum_players, :price, :description, :genre, :picture, :search)
    end

    # Only allow admin or game seller to do select actions
    def check_ownership
      if !(current_user.admin? or current_user.id == @game.user_id)
        redirect_to games_url, alert: "You have to be the seller of a game or an admin to do this."
      end
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :genre %><br>
    <%= form.select :genre, Game.genres.keys %>
  </div>

  <div class="field">
    <%= form.label :condition %><br>
    <%= form.select :condition, Game.conditions.keys %>
  </div>

  <div class="field">
    <%= form.label :minimum_players %><br>
    <%= form.number_field :minimum_players, min: 1 %>
  </div>

  <div class="field">
    <%= form.label :maximum_players %><br>
    <%= form.number_field :maximum_players, min: 1 %>
  </div>

  <div class="field">
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :picture %><br>
    <%= form.file_field :picture, accept: "image/jpg, image/jpeg, image/png" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path, class: "btn btn-primary my-2" %>

app/views/games/index.html.erb
<h1>Games</h1>


<div class="row row-cols-1 row-cols-md-4 g-4">
  <% @games.each do |game| %>
    <div class="col">
      
        <div class="card" style="width: 18rem;">
          <div class="card-img-top" alt="Game main image">
            <% if game.picture.attached? %>
              <%= image_tag game.picture, class: "img-thumbnail" %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= game.name %></h5>
            <p class="card-text">
              <strong>Genre:</strong>
              <%= game.genre %>
            </p>
            <p class="card-text">
              <strong>Price:</strong>
              $<%= game.price %>
            </p>

            <% if game.sold %>
              <h2>SOLD</h2>
            <% end %>
            <p><%= link_to 'Show', game, class: "btn btn-primary my-2" %></p>
          </div>
          
      </div>
    </div>  
  <% end %>
</div>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path, class: "btn btn-primary my-2" %>

app/views/games/search.html.erb
<h3>Search Results</h3>

<% # Displays when a user uses the search bar %>
<%= link_to 'Back', games_path %><br>
<br><br>
<div class="row row-cols-1 row-cols-md-4 g-4">
  <% @results.each do |result| %>
    <div class="col">
      
        <div class="card" style="width: 18rem;">
          <div class="card-img-top" alt="Game main image">
            <% if result.picture.attached? %>
              <%= image_tag result.picture, class: "img-thumbnail" %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= result.name %></h5>
            <p class="card-text">
              <strong>Genre:</strong>
              <%= result.genre %>
            </p>
            <p class="card-text">
              <strong>Price:</strong>
              $<%= result.price %>
            </p>
            <p><%= link_to 'Show', result %></p>
          </div>
          
      </div>
    </div>  
  <% end %>
</div>

app/views/games/show.html.erb
<div class="card mb-3" style="max-width: 100%;">
<div class="row g-0">
  <div class="col-md-4">
    <div class="img-fluid rounded-start" alt="Boardgame image">
      <% if @game.picture.attached? %>
        <%= image_tag @game.picture.representation(resize_to_limit: [400,400]).processed, :crop => :fill %>
      <% end %>
    </div>
  </div>
  <div class="col-md-8">
    <div class="card-body">
      <h5 class="card-title"><%= @game.name %></h5>
      <p>
        <strong>Price:</strong>
        <%= @game.price %>
      </p>
      <p>
        <strong>Seller:</strong>
        <%= @game.user.username %>
      </p>
      <p class="card-text"><%= @game.description %></p>

      <p>
        <strong>Genre:</strong>
        <%= @game.genre %>
      </p>
      <p>
        <strong>Players:</strong>
        <%= @game.minimum_players %> to <%= @game.maximum_players %>
      </p>
      <p>
        <strong>Condition:</strong>
        <%= @game.condition %>
      </p>

      <p>
        <strong>Location:</strong>
        <%= @game.user.address.street_name %>, <%= @game.user.address.suburb %>, <%= @game.user.address.postcode %>
      </p>
      
      <% if @game.sold === true %>
        <h2>SOLD</h2>
      <% end %>


      <% # Stop the user from being able to buy their own game %>
      <% if user_signed_in? and (current_user.id != @game.user_id) and (@game.sold != true) %>
        <%= link_to "Buy it now", new_game_purchase_path(@game.id), class: "btn btn-primary my-2" %>
      <% end %>

      <% if user_signed_in? and (current_user.admin? or current_user.id == @game.user_id) %> 
        <%= link_to 'Edit', edit_game_path, class: "btn btn-secondary my-2" %>
        <%= link_to 'Destroy', @game, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-secondary my-2" %>
      <% end %>
      <%= link_to 'Back', games_path, class: "btn btn-primary my-2" %>
    </div>
  </div>
</div>
</div>