config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Send back the home page
  get "pages/index"
  root to: "pages#index"
  
  # Send back all addresses to the client for Admin use
  get 'addresses', to: 'addresses#index'
  # Create new addresses
  post 'addresses', to: 'addresses#create'
  get 'addresses/new', to: 'addresses#new'
  # Send back one address to the client
  get 'addresses/:id', to: 'addresses#show', as: 'address'
  # Edit an address
  get 'addresses/:id/edit', to: 'addresses#edit', as: "edit_address"
  patch 'addresses/:id', to: 'addresses#update'
  put 'addresses/:id', to: 'addresses#update'
  
  get '/mypurchases', to: 'purchases#index', as: "my_purchases"
  
  # Search for games 
  get '/search', to: 'games#search'
  resources :games do
    resources :purchases, only:[:new, :create, :index]
  end

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
    before_action :set_address, only: %i[ show edit update destroy ]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    before_action :check_ownership, only: [:show, :edit, :update, :destroy]

    # GET /addresses
    def index
        @addresses = Address.all
    end

    # GET /addresses/1
    def show
        @address = Address.find(params[:id])
    end

    # GET /addresses/new
    def new
        @address = Address.new
    end

    # GET /addresses/1/edit
    def edit
    end

    # POST /games
    def create
        begin
            # Ensure correct params are passed
            Address.new(street_number: address_params[:street_number], street_name: address_params[:street_name], suburb: address_params[:suburb], state: address_params[:state], postcode: address_params[:postcode], user: current_user)
            # No redirect here as address is created together with User creation in Devise
        rescue StandardError => e
            puts e.message
            redirect_to games_path, notice: "Address wasn't created"
        end  
    end

    # PATCH/PUT /addresses/1
    def update
        respond_to do |format|
            if @address.update(address_params)
                format.html { redirect_to game_url, notice: "Address was successfully updated." }
            else
                format.html { render :edit, status: :unprocessable_entity }
            end
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
        begin
            @address = Address.find(params[:id])
        rescue StandardError => e
            puts e.message
            redirect_to games_path, alert: "Application is trying to access an address id #{params[:id]} doesn't exist in the database"
        end
    end

    # Only allow a list of trusted parameters through.
    def address_params
        params.require(:address).permit(:street_number, :street_name, :suburb, :state, :postcode)
    end

    # Only allow admin or address owner to do select actions
    def check_ownership
        if !(current_user.admin? or current_user.id == @address.user_id)
          redirect_to games_url, alert: "You have to be the authorised user or an admin to do this."
        end
    end
end

app/views/addresses/_form.html.erb
<h1>Add your address</h1>

<%= form_with model: @address do |form| %>
    <div class="field">
        <%= form.label :street_number %>
        <%= form.number_field :street_number, required:true %>
    </div>

    <div class="field">
        <%= form.label :street_name %>
        <%= form.text_field :street_name, required:true %>
    </div>

    <div class="field">
        <%= form.label :suburb %>
        <%= form.text_field :suburb, required:true %>
    </div>

    <div class="field">
        <%= form.label :state %>
        <%= form.text_field :state, required:true %>
    </div>

    <div class="field">
        <%= form.label :postcode %>
        <%= form.text_field :postcode, required:true %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/addresses/_form2.html.erb
<%= form_with model: @address do |form| %>
    <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
    <div class="field">
        <%= form.label :street_number %>
        <%= form.number_field :street_number, required:true %>
    </div>

    <div class="field">
        <%= form.label :street_name %>
        <%= form.text_field :street_name, required:true %>
    </div>

    <div class="field">
        <%= form.label :suburb %>
        <%= form.text_field :suburb, required:true %>
    </div>

    <div class="field">
        <%= form.label :state %>
        <%= form.text_field :state, required:true %>
    </div>

    <div class="field">
        <%= form.label :postcode %>
        <%= form.text_field :postcode, required:true %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Edit your address</h1>
<% # Use the same form as the new view %>
<%= render 'form2', address: @address %>


<%= link_to 'Back', address_path, class: "btn btn-primary my-2" %>

app/views/addresses/index.html.erb
<h1>Addresses Index</h1>
<% # Is intended for use by the admin, but there is a glitch that allows some users to view it instead of their own data %>
<% @addresses.each do |address| %>
    
    <p>
      <strong>User:</strong>
      <%= address.user.username %>
    </p>
    <p>
      <strong>Street:</strong>
      <%= address.street_number %> <%= address.street_name %>
    </p>

    <p>
      <strong>Suburb:</strong>
      <%= address.suburb %>
    </p>

    <p>
      <strong>State:</strong>
      <%= address.state %>
    </p>

    <p>
      <strong>Postcode:</strong>
      <%= address.postcode %>
    </p>
  
    <% if user_signed_in? and (current_user.admin? or current_user.id == address.user_id) %> 
    <p><%= link_to 'Show', address %></p>
      <%= link_to 'Destroy', @address, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <%= link_to 'Back', pages_index_path %>


  <% end %>

app/views/addresses/new.html.erb
<h1>Add your address</h1>
<% # Use the same form as the edit view %>
<%= render 'form2', address: @address %>

app/views/addresses/show.html.erb
<% # This data should be unavailable if you are neither the owner or admin %>
<% if user_signed_in? and (current_user.admin? or current_user.id == @address.user_id) %> 

    <h1>My details</h1>
    
    <h2>User</h2>
    <p><strong>Username:</strong> <%= current_user.username %></p>
    <p><strong>Email:</strong> <%= current_user.email %></p>
    <%= link_to 'Edit', edit_user_registration_path, class: "btn btn-secondary my-2" %>
    <h2>Address</h2>
    <p>Street: <%= @address.street_number %> <%= @address.street_name %></p>
    <p>Suburb: <%= @address.suburb %></p>
    <p>Postcode: <%= @address.postcode %></p>
    <p>State: <%= @address.state %></p>

    <%= link_to 'Edit', edit_address_path, class: "btn btn-secondary my-2" %> 
<% end %>
<br><br>
<%= link_to 'Back', pages_index_path %>